import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import VueECharts from "vue-echarts";
import "./assets/tailwind.css";
import "./assets/fonts.css";
import naive from "naive-ui";
const app = createApp(App);
app.use(router);
app.use(naive);
app.component("v-chart", VueECharts);
app.mount("#app");
